### ISSUE TITLE
MissingAuthenticationTokenException

### ISSUE THREAD

**Issue by hbbio** [mhart/dynalite#105]
I am performing two subsequent queries (from a Go client):

The first put query executes successfully:

```go
&dynamodb.PutItemOutput{
  _:                     struct {}{},
  Attributes:            map[string]*dynamodb.AttributeValue{},
  ConsumedCapacity:      (*dynamodb.ConsumedCapacity)(nil),
  ItemCollectionMetrics: (*dynamodb.ItemCollectionMetrics)(nil),
}
```

but the second put fails with the following error:

```go
&awserr.requestError{
  awsError: &awserr.baseError{
    code:    "MissingAuthenticationTokenException",
    message: "Request is missing Authentication Token",
    errs:    []error{},
  },
  statusCode: 400,
  requestID:  "NIGX0KAH4ENLNOGCJJQZFBJMUFQHCMUHXB0INRN560W0AHYGDNSD",
}
```

Any idea to what could be the cause? I haven't seen much documentation about query auth as I guess there's none for local tests.

Edit: Both put requests come from the same function with similar arguments.

**Comment by hbbio** [comment]
Turns out that in between calls I added an Authorization header to the RoundTripper. Should dynalite ignore Authorization headers? 

(btw, the error message is wrong since adding an Authorization header triggers the error while it seems from the message it's the other way round)

**Comment by mhart** [comment]
No, dynalite will always expect an Authorization header – it's intended to act as much like production as possible, so that your tests are as accurate as possible. I imagine that this would have failed in production too (if it doesn't, then you'll need to explain a bit more what's going on and how you're getting it to succeed at Authorization in production)

**Comment by hbbio** [comment]
Thanks @mhart makes sense.
