### ISSUE TITLE
S3 serialization

### ISSUE THREAD

**Issue by chadbrewbaker** [mhart/dynalite#135]
What would it take to turn this into a Lambda layer with serialization to S3 so you could use it in production and avoid DynamoDB altogether?

**Comment by mhart** [comment]
If you used [EFS](https://aws.amazon.com/blogs/aws/new-a-shared-file-system-for-your-lambda-functions/) (instead of S3), you wouldn't need to modify anything at all.

I still wouldn't recommend using it in production though – it hasn't really been stress tested in the way you'd want to for a production DB.

**Comment by urbien** [comment]
I also would like to do this, and EFS is fine with me. But I can't call Dynalite in Lambda as it is implemented as a HTTP server, to emulate DynamoDB. I want to skip the whole aws-client and use Dynalite as embedded DB, and experiment with other LevelUP backends. 
@mhart can you suggest the best way to cut through and call Dynalite as API?

**Comment by mhart** [comment]
@urbien can you explain what problems you have calling this in Lambda? It should work totally fine

**Comment by urbien** [comment]
@mhart thanks for the quick reply! Dynalite is awesome and it is clear you put immense amount of work into it. 
In Lambda I certainly do not need an HTTP server, and I do not even know if can have HTTP client talk to HTTP server inside the same nodejs process of Lambda function. May be it is possible, but certainly very inefficient.

**Comment by mhart** [comment]
You can certainly do that – explain the inefficiency to me?

**Comment by urbien** [comment]
Inefficiency is in serializing the request to a string to be sent over the wire, making HTTP request, receiving it and deserializing on the other end. More in AWS client which is adding a signature to the request. All of that is not needed if calling the API directly. 
We would still need to convert a JavaScript object to its equivalent DynamoDB AttributeValue type with https://github.com/aws/aws-sdk-js/blob/master/lib/dynamodb/converter.js#L7

**Comment by mhart** [comment]
Any time serializing is insignificant compare with the time it'll take you to perform I/O to your LevelUp backend – *especially* if it's EFS – you're talking dozens, if not hundreds, of milliseconds for each EFS interaction – compared with nanoseconds for string manipulation in JS.

**Comment by urbien** [comment]
agree, but although I will test with EFS, my target environment is something very different. We are building an open source Personal Cloud, which will have Lambda-like execution environment and single-tenant personal data management with a personal file system, personal database, personal reliable messaging, etc. If interested, I would be thrilled to share the details with you.

**Comment by mhart** [comment]
Ok, no probs. I'm still of the opinion that any time doing external I/O will be much slower than any local HTTP interactions – unless you're talking to an in-memory or local store, in which case, it wouldn't really make sense on Lambda (or a Lambda-like environment) because the data wouldn't be shared. You'd be much better off hosting the DB separately.

In any case, going to close this out – it's not a scenario that I think dynalite should support. Nor do I have any plans to support an API here beyond the DynamoDB API contract.

If you'd like to fork it and create your own API, the http server is really just a light wrapper around the DB store. You can see the store created here:

https://github.com/mhart/dynalite/blob/58d0955a5441ed294a92ce7bb109d7b2d88da1a1/index.js#L24

And how actions are called on it here:

https://github.com/mhart/dynalite/blob/58d0955a5441ed294a92ce7bb109d7b2d88da1a1/index.js#L261
