### ISSUE TITLE
Can't connect to Dynalite using Boto

### ISSUE THREAD

**Issue by jschlather** [mhart/dynalite#28]
>>> conn = DynamoDBConnection(aws_access_key_id='x', aws_secret_access_key='y', host='0.0.0.0', port=8000, is_secure=False)
    >>> conn.list_tables()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Library/Python/2.7/site-packages/boto/dynamodb2/layer1.py", line 1090, in list_tables
        body=json.dumps(params))
      File "/Library/Python/2.7/site-packages/boto/dynamodb2/layer1.py", line 2731, in make_request
        retry_handler=self._retry_handler)
      File "/Library/Python/2.7/site-packages/boto/connection.py", line 953, in _mexe
        status = retry_handler(response, i, next_sleep)
      File "/Library/Python/2.7/site-packages/boto/dynamodb2/layer1.py", line 2774, in _retry_handler
        data)
    boto.exception.JSONResponseError: JSONResponseError: 400 Bad Request
    {u'message': u"Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization=AWS4-HMAC-SHA256 Credential=x/20150320/168/192/aws4_request,SignedHeaders=host;x-amz-date;x-amz-target,Signature=252305f17ba2763e705b6818f68077cba9627a338574b4fd9d0635be79b67d5b", u'__type': u'com.amazon.coral.service#IncompleteSignatureException'}

If I remove the is_secure from the command, then dynalite hangs on the request.

**Comment by mhart** [comment]
Authorization is definitely needed (to emulate production), so those errors look like it's not being passed through when `is_secure` is false (no surprise there I guess)

The hung request is a bit more interesting, I'm not sure what's causing that. Been a while since I fired up Python, but I'll give it a shot and see what might be causing it.

**Comment by mhart** [comment]
Actually, turns out I'm wrong :smile_cat: 

`is_secure` is just for SSL – so that should be false.

The problem is caused by the way Boto is constructing its authorization header – it's not the same as the way used in the documentation: http://docs.aws.amazon.com/general/latest/gr/sigv4-add-signature-to-request.html – there are no spaces in between params.

I'll fix this in dynalite now – thanks for the report!

**Comment by mhart** [comment]
Fixed and published in v0.9.2

Thanks again for filing this.
