### ISSUE TITLE
Update README to reflect updated comparison with newer DynamoDBLocal (2015-07-06)

### ISSUE THREAD

**Issue by chook** [mhart/dynalite#40]
https://github.com/mhart/dynalite#problems-with-amazons-dynamodb-local contains a long list of problems that may or may not be still relevant. Is there an updated list?

**Comment by tiagobrito** [comment]
@mhart Do you have an ETA for this? I think that at this point the AWS dynamodb-local is probably more reliable than dynalite, it would be great to have your feedback.

**Comment by mhart** [comment]
@tiagobrito I'd certainly love to know where dynalite is unreliable, please file issues for that.

The documentation was written for the version of dynamodb-local at the time, which was years ago, so probably doesn't apply to the latest version – I think AWS have fixed loads of bugs since then.

It was quite a lot of work to compare each feature, so this will have to wait until I (or anyone) has time unfortunately.

**Comment by tiagobrito** [comment]
@mhart Don't undersand me worng. I didn't say it was "unreliable" in any part of my comment. My point is that the current statements that you have on documentation can be missleading at the current date.

**Comment by mhart** [comment]
Er, that's splitting hairs. Ok, please let me know where dynalite is *less* reliable than dynamodb-local.

**Comment by tiagobrito** [comment]
I open this https://github.com/mhart/dynalite/issues/46 for example

**Comment by mhart** [comment]
Cool, thanks! I'll look into it.

**Comment by mhart** [comment]
This has been updated as of v1.0.0
