### ISSUE TITLE
Callbacks get fired too early when using AWS.DynamoDB.createTable

### ISSUE THREAD

**Issue by JoshTumath** [mhart/dynalite#73]
## Steps to reproduce
Try running the following script with dynalite running on port 4567:

```javascript
const AWS = require('aws-sdk');

AWS.config.update({
    region: 'eu-west-1',
    endpoint: 'http://localhost:4567'
});

const db = new AWS.DynamoDB();
const dbClient = new AWS.DynamoDB.DocumentClient();

db.createTable({
    TableName: 'test-string',
    KeySchema: [
        { AttributeName: 'key', KeyType: 'HASH' }
    ],
    AttributeDefinitions: [
        { AttributeName: 'key', AttributeType: 'S' }
    ],
    ProvisionedThroughput: {
        ReadCapacityUnits: 10, 
        WriteCapacityUnits: 10
    }
}, (error) => {
    console.log('1');
    if (error) { console.log(error); return; }

    db.createTable({
        TableName: 'test-int',
        KeySchema: [
            { AttributeName: 'key', KeyType: 'HASH' }
        ],
        AttributeDefinitions: [
            { AttributeName: 'key', AttributeType: 'S' }
        ],
        ProvisionedThroughput: {
            ReadCapacityUnits: 10, 
            WriteCapacityUnits: 10
        }
    }, (error) => {
        console.log('1=2');
        if (error) { console.log(error); return; }

        dbClient.put({
            TableName: 'test-int',
            Item: {
                'key': 'A'
            }
        });
    });
});
```

When this script is run, we get `ResourceNotFoundException: Requested resource not found`

## Problem
When using `createTable`, the callback is fired instantly rather than after the table is created. As a result, the `put` method in the example above is being called before the table even exists.

**Comment by mhart** [comment]
Right – DynamoDB tables aren't created immediately (well not so that you can put items in them) and you'll need to ensure that your code deals with this. The production version of DynamoDB will return from the callback immediately as well.

The table will be in the `CREATING` state when it's first created. By default, `dynalite` keeps the table in this state for 500 milliseconds – although production will usually be a bit longer than that.

If you *do* want to reduce this time, you can do it with the various command line flags as specified here: https://github.com/mhart/dynalite#example

**Comment by mhart** [comment]
BTW – the JS SDK has methods for this that you might want to use: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#tableExists-waiter

**Comment by JoshTumath** [comment]
I didn't realise DynamoDB was the same. Thanks for the very useful links in your response! 👍
